import Head from 'next/head'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'
import CardEdital from '@/components/CardEdital'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NuConnect - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://nubank.com.br/images/open-graph-logo.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}` }>
        <div className={ styles.gridSidebar}>

        
        <Sidebar/>
        <div>
        <section className={styles.sectionBanner} >
          <div className={styles.collumnDescription} style={{justifyContent:"center", paddingLeft:'0px'}}>
            <h1 className={styles.title}>Olá! É bom te ver aqui!</h1>
            <p className={styles.description}>
            A Plataforma NuConnect é uma solução digital para ação social com impacto real. Criada para empresas, ONGs e indivíduos, a NuConnect promove transparência e eficiência na execução de projetos sociais, alinhando-se aos princípios ESG (Ambiente, Social e Governança).
            </p>
          </div>
          <div className={styles.collumnImage} style={{ alignItems: "start"}}> 
            <Image 
                src="/Welcome-rafiki1.png"
                width={377}
                height={436}
                alt="NuConnect"
              />
          </div>
        </section>
            
            <section className={styles.sectionEditais} style={{    padding: "2% 5%"}}>
            <h2 className={styles.title} style={{fontWeight:600}}>Editais abertos</h2>
            <Link href="/editais" className={styles.smallTitle}>Visualizar todos os editais </Link>
            <div className={styles.gridCard}>
                <CardEdital/>
                <CardEdital/>
                <CardEdital/>
                <CardEdital/>
                <CardEdital/>
            </div>
            </section>
        </div>
        
       
        </div>
      </main>
    </>
  )
}
