import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Link from 'next/link'
import LoginIcon from '@/icons/LoginIcon'
import CardEdital from '@/components/CardEdital'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NuConnect - Início</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://nubank.com.br/images/open-graph-logo.png" />
      
    
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Navbar>
          <Link href="/login" className={styles.linkButton}>Conectar</Link>
          <LoginIcon/>
        </Navbar>
        <section className={styles.sectionBanner}>
          <div className={styles.collumnDescription}>
            <h1 className={styles.title}>Plataforma fácil de usar</h1>
            <p className={styles.description}>
              A Plataforma NuConnect é uma solução digital para ação social com impacto real. Criada para empresas, ONGs e indivíduos, a NuConnect promove transparência e eficiência na execução de projetos sociais, alinhando-se aos princípios ESG (Ambiente, Social e Governança).
            </p>
            <p className={styles.description}> 
              O principal objetivo é conectar proponentes comprometidos com um futuro sustentável a investidores dispostos a fazer a diferença. Junte-se a nós e faça parte dessa jornada em direção a um mundo melhor.
            </p>
          </div>
          <div className={styles.collumnImage}> 
            <Image 
                src="/image-banner.png"
                width={448}
                height={399.9}
                alt="NuConnect"
              />
          </div>
        </section>
        <section className={styles.sectionEditais}>
          <h2 className={styles.title} style={{fontWeight:600}}>Editais abertos</h2>
          <Link href="/editais" className={styles.smallTitle}>Visualizar todos os editais </Link>
          <div className={styles.gridCard}>
            <CardEdital/>
            <CardEdital/>
            <CardEdital/>
            <CardEdital/>
            <CardEdital/>
          </div>
        </section>

      </main>
    </>
  )
}
